### ISSUE TITLE
Doc links broken

### ISSUE THREAD

**Issue by oyeanuj** [lukesmurray/use-slate-with-extensions#16]
Hey @lukesmurray! Firstly, just wanted to say thank you for building this library. Since upgrading from 0.36 to the latest version of the library, I've been struggling with how the original plugin encapsulation doesn't work any more (the split into editor and editable). And I think this library might help make code easier to write and reason. 

FYI  - As I was going through the docs, noticed that a few links in the API section of the README were broken:
https://github.com/lukesmurray/use-slate-with-extensions#slateextension-functions
https://github.com/lukesmurray/use-slate-with-extensions#useslatewithextensionsoptions

**Comment by lukesmurray** [comment]
thanks for opening the issue i'll make sure those links are fixed!

**Comment by lukesmurray** [comment]
Fixed in [407f55e](https://github.com/lukesmurray/use-slate-with-extensions/commit/407f55e48343dda9a7346bdacb35ef62e85961ff)

Thank you
