### ISSUE TITLE
Clarify deps in SlateExtension 

### ISSUE THREAD

**Issue by oyeanuj** [lukesmurray/use-slate-with-extensions#17]
Hey @lukesmurray, quick question. Most of the library seems clear but I was a little unclear on what 'deps' are for all of the methods listed here, for instance `onChangeDeps`:
https://github.com/lukesmurray/use-slate-with-extensions/blob/master/src/core/types/SlateExtension.ts

Maybe I'm just not thinking straight but what are the kind of plugins/actions I'd need to make sure to have deps for?

**Comment by lukesmurray** [comment]
think of them as similar to dependencies you would use for any other hook. if you wrote your onchange callback using usecallback you would have the same dependencies. does that answer your question?

**Comment by lukesmurray** [comment]
an example dependency would be a save function or an object for communicating with a database/api

**Comment by lukesmurray** [comment]
let me know if you have any further issues and I'll reopen!
