### ISSUE TITLE
Handle copy/paste in an extension

### ISSUE THREAD

**Issue by dan-lee** [lukesmurray/use-slate-with-extensions#2]
Hey @lukesmurray!

Thanks a lot for your great library, this makes it a breeze to extend the editor in a structured manner.
I am currently trying to implement paste and I am only able to do it in a 'global' way:

```ts
const { getSlateProps, getEditableProps, editor } = useSlateWithExtensions({
  // …
}

// either overwriting ReactEditor.insertData
useEffect(() => {
  editor.insertData = (data) => {
    handlePaste(data.getData('text/plain'))
  }
}, [])

// or as a handler on Editable:

<Slate {...getSlateProps()}>
  <Editable
    {...getEditableProps()}
    onPaste={(e) => {
      handlePaste(e.clipboardData.getData('text/plain'))
    }}
  />
</Slate>
```

But neither of those solutions scale elegantly for more than one extension. I am wondering if you have an idea of how to integrate it into your extension system.

I think copying needs to be handled similarly (but is not one of my concerns right now)

Thanks a lot :)

**Comment by lukesmurray** [comment]
Thanks for raising the issue. This looks easy to address at first glance but I'm on vacation for the next couple of days. I'll try to get a fix out once I get back.

**Comment by lukesmurray** [comment]
@dan-lee I haven't dealt with pasting data so I want to make sure I completely understand your problem before I code a solution. `Slate` lets users handle paste events in two ways. You can modify `editor.insertData` or add an `onPaste` handler to the `Editable`. 

I noticed that both these methods are missing from the extensions api. Would adding `insertData` and `onPaste` to the extensions api solve your problem? You would still need to potentially handle paste in two places but at least this could be done inside of an extension and not in a global way.

While looking at this I noticed the following methods missing from the  extensions API. I'll probably add all of these in one Pull request to avoid future issues.

**Methods to add to the ReactEditor props**

(These don't exist on default Editor, so potentially check for reactEditor support before adding)

- [ ] insertData
- [ ] setFragmentData
- [ ] hasRange

**Methods to add to the Editable props**

- [x] `onBeforeInput`
- [ ] `onBlur`
- [ ] `onClick`
- [ ] `onCompositionEnd`
- [ ] `onCompositionUpdate`
- [ ] `onCompositionStart`
- [ ] `onCopy`
- [ ] `onCut`
- [ ] `onDragOver`
- [ ] `onDragStart`
- [ ] `onDrop`
- [ ] `onFocus`
- [x] `onKeyDown`
- [ ] `onPaste`

**Comment by dan-lee** [comment]
Hey @lukesmurray, thanks for your reply and time! Hope you had a great vacation :)

I think either way would fix the problem! I am still fairly new to Slate, but I think the key difference (from what I can tell) is that when `editor.insertData` is registered, it's up to the implementation to handle what to do. With `onPaste` you still get a `ClipboardEvent` and can call `preventDefault` to actually stop pasting the text. Maybe there are other nuances I am not aware of.

To stay consistent with the rest of the extensions API, I would suggest implementing `insertData` which is part of the `ReactEditor`, not the `BaseEditor` as you also mentioned, if that makes a difference.

**Comment by lukesmurray** [comment]
@dan-lee this should all be fixed. There was a small breaking change, `withHistory` now works out of the box and can be assigned to `prePlugins`. `plugins` was renamed `postPlugins`. If you're just using extensions then none of this applies to you but let me know if you have any issues.

**Comment by dan-lee** [comment]
@lukesmurray Thanks a lot for your work! Sorry for the late reply, kinda busy schedule. I will try it out on the weekend

**Comment by lukesmurray** [comment]
np this improves the extensions for everyone! thanks for reporting the usability issues!
